---
title: "EDS 221 day 7 interactive"
author: "Stephen Carroll"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)
```

## Refresher 1
```{r}
# make a subset of data that only includes penguins form Biscoe and Dream islands, with the year and sex removed. add a new column with body mass converted to kg and rename the island variable to location

penguins <- penguins

penguins_bd <- penguins %>%
  filter(island %in% c("Biscoe", "Dream" ))%>%
  select(-"sex", -"year")%>%
  mutate(body_mass_kg = body_mass_g / 1000)%>%
  dplyr::rename(location = island)
  
```

## Refresher 2
```{r}
#*
penguins_adelie <- penguins %>%
  filter(species == "Adelie" & !is.na(flipper_length_mm))%>%
  group_by(sex) %>%
  summarise(mean_flipper_length = mean(flipper_length_mm, na.rm = TRUE),
            sd_flipper_length = sd(flipper_length_mm, na.rm = TRUE),
            sample_size = n())
```

```{r}
animals <- tibble::tribble(
  ~location,   ~species,  ~maturity,
   "lagoon",   "bobcat",    "adult",
    "bluff",   "coyote", "juvenile",
    "creek",      "fox",    "adult",
     "oaks", "squirrel", "juvenile",
    "bluff",   "bobcat",    "adult"
  )
```

```{r}
sites <- tibble::tribble(
           ~location,      ~full_site_name, ~jurisdiction,
             "beach",       "Goleta Beach",     "SB City",
            "lagoon",        "UCSB Lagoon",        "UCSB",
             "bluff",       "Ellwood Mesa",     "SB City",
              "oaks", "Fremont Campground",        "USFS"
           )

```


```{r}
# full join example
full_join_example <- full_join(animals, sites)
```

```{r}
#left join example
left_join_example <- left_join(animals, sites)
```

```{r}
# right join example
right_join_example <- right_join(animals, sites)
```


```{r}
# inner join example
inner_join_example <- inner_join(animals, sites)
```

```{r}
# semi join example
semi_join_example <- semi_join(animals, sites)
semi_join_test<- animals %>%
  filter(location %in% sites$location)
```

```{r}
#anti join example
anti_join_example <- anti_join(animals, sites, by = "location")

anti_join_test <- animals %>%
  filter(!location %in% sites$location)
```

```{r}
sites <- sites %>%
  rename(place = location)

test_join <- full_join(animals, sites, (by = c("location" = "place")))
```






